name: Wakatime

on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: "*/2 * * * *"

jobs:
  update-readme:
    name: Wakatime
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: all_time
